server:
  port: 8084
  servlet:
    context-path: "/api"

spring:
  datasource:
    password: "2004"
    username: "zarate"
    url: "jdbc:mysql://localhost:3306/springboot"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update